targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: foodio|lib/core/graphql/strapi_schema.graphql
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: foodio|lib/core/graphql/strapi_schema.graphql
